/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    FriendCheckbox: typeof import('./components/FriendCheckbox.vue')['default']
    FriendEmailList: typeof import('./components/FriendEmailList.vue')['default']
    FriendFormCard: typeof import('./components/FriendFormCard.vue')['default']
    FriendNumberInput: typeof import('./components/FriendNumberInput.vue')['default']
    FriendRadioGroup: typeof import('./components/FriendRadioGroup.vue')['default']
    FriendSelect: typeof import('./components/FriendSelect.vue')['default']
    FriendTextarea: typeof import('./components/FriendTextarea.vue')['default']
    FriendTextField: typeof import('./components/FriendTextField.vue')['default']
    LoginStepEmail: typeof import('./components/login/LoginStepEmail.vue')['default']
    LoginStepOtp: typeof import('./components/login/LoginStepOtp.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
