/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    FriendCheckbox: typeof import('./components/FriendCheckbox.vue')['default']
    FriendFormCard: typeof import('./components/FriendFormCard.vue')['default']
    FriendRadioGroup: typeof import('./components/FriendRadioGroup.vue')['default']
    FriendTextarea: typeof import('./components/FriendTextarea.vue')['default']
    FriendTextField: typeof import('./components/FriendTextField.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
